language: C++
dist: Bionic
script:
  - cmake .
  - make
before_install:
  - pip install conan
  - conan install . --build bzip2 --build zlib --build boost
addons:
  apt:
    update: true
    packages: cmake python-pip



